---
- name: config tors
  hosts: localhost
  vars:
    config_dir: /var

  tasks:
    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
      - "{{ config_dir }}/.aws"
      - "{{ config_dir }}/.evalai"
    
    - name: aws config
      template:
        src: config.j2
        dest: "{{config_dir }}/.aws/config"
    
    - name: evalai config
      template:
        src: worker_config.json
        dest: "{{ config_dir }}/.evalai/worker_config.json"
...
