---
- name: python script from git repo as service
  hosts: localhost
  # gather_facts: true
  vars:
    git_dir: /opt

  tasks:
    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{ git_dir }/{{ repo | basename }}"
      environment:
        GIT_TERMINAL_PROMPT: 0

    - name: Create service file from template
      template:
        src: python_script.service.j2
        dest: /etc/systemd/system/python_script.service
    
    - name: Start python script
      systemd:
        name: python_script
        state: started
        enabled: yes
...
